services:
  planka-webhook-receiver:
    image: ghcr.io/c4sti3l/planka-webhook-receiver:latest
    container_name: planka-webhook-receiver
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_INITIAL_PASSWORD=${ADMIN_INITIAL_PASSWORD:-admin123}
      # - WEBHOOK_SECRET=${WEBHOOK_SECRET}
